name: SupremeExpansion
author: RelativoBR
description:  more slimefun content in supreme expansion
main: br.com.ohanacraft.supremeexpansion.SupremeExpansion
website: https://github.com/OhanaCraft/SupremeExpansion-Public
depend: [Slimefun]
version: ${project.version}
api-version: 1.16